import type { Product } from "@/components/product-card"

// Datos de ejemplo de productos
export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Vaper Pro X1 - Dispositivo Premium",
    price: 89.99,
    image: "/modern-sleek-vape-device-black.jpg",
    category: "vaper",
    rating: 5,
    inStock: true,
    featured: true,
  },
  {
    id: "2",
    name: "E-Liquid Mango Tropical 60ml",
    price: 24.99,
    image: "/vape-juice-bottle-mango-flavor.jpg",
    category: "eliquid",
    rating: 4,
    inStock: true,
  },
  {
    id: "3",
    name: "Vaper Mini Compact - Portátil",
    price: 49.99,
    image: "/compact-portable-vape-device.jpg",
    category: "vaper",
    rating: 4,
    inStock: true,
  },
  {
    id: "4",
    name: "E-Liquid Fresa Crema 60ml",
    price: 19.99,
    image: "/vape-juice-bottle-strawberry-cream.jpg",
    category: "eliquid",
    rating: 5,
    inStock: true,
    featured: true,
  },
  {
    id: "5",
    name: "Kit de Resistencias Premium x5",
    price: 19.99,
    image: "/vape-coils-replacement-kit.jpg",
    category: "accesorio",
    rating: 4,
    inStock: true,
  },
  {
    id: "6",
    name: "E-Liquid Menta Fresca 60ml",
    price: 22.99,
    image: "/vape-juice-bottle-mint-flavor.jpg",
    category: "eliquid",
    rating: 4,
    inStock: false,
  },
  {
    id: "7",
    name: "Vaper Elite RGB - Edición Limitada",
    price: 129.99,
    image: "/rgb-led-vape-device-premium.jpg",
    category: "vaper",
    rating: 5,
    inStock: true,
    featured: true,
  },
  {
    id: "8",
    name: "E-Liquid Café Vainilla 60ml",
    price: 26.99,
    image: "/vape-juice-bottle-coffee-vanilla.jpg",
    category: "eliquid",
    rating: 5,
    inStock: true,
  },
]

export const PRODUCT_DESCRIPTIONS: Record<string, string> = {
  "1": "El Vaper Pro X1 es nuestro dispositivo insignia, diseñado para vapeo de alto rendimiento. Con tecnología de última generación, batería de larga duración y control de temperatura preciso, ofrece una experiencia premium inigualable.",
  "2": "Disfruta del sabor tropical del mango maduro en cada calada. Nuestro e-liquid premium está elaborado con ingredientes de la más alta calidad, proporcionando un sabor auténtico y una producción de vapor excepcional.",
  "3": "Perfecto para llevar a todas partes. El Vaper Mini Compact combina portabilidad con rendimiento, ofreciendo una experiencia de vapeo satisfactoria en un formato ultracompacto.",
  "4": "Una deliciosa combinación de fresas frescas con crema suave. Este e-liquid es uno de nuestros favoritos, con un perfil de sabor equilibrado que te encantará.",
  "5": "Mantén tu dispositivo funcionando al máximo con nuestras resistencias premium. Pack de 5 unidades de alta calidad para un vapeo consistente y duradero.",
  "6": "Refrescante y vigorizante, nuestro e-liquid de menta fresca es perfecto para quienes buscan una experiencia limpia y refrescante.",
  "7": "Edición limitada con iluminación RGB personalizable. El Vaper Elite combina estilo y rendimiento en un dispositivo único que destaca en cualquier lugar.",
  "8": "Para los amantes del café, este e-liquid combina el rico sabor del café con notas suaves de vainilla. Perfecto para cualquier momento del día.",
}
